"""empty message

Revision ID: 5a25b15701ae
Revises: b5ae00a23155
Create Date: 2026-02-01 22:08:14.095077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a25b15701ae'
down_revision = 'b5ae00a23155'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=200), nullable=True),
    sa.Column('memories_count', sa.Integer(), nullable=True),
    sa.Column('diaries_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_buildings')),
    sa.UniqueConstraint('name', name=op.f('uq_buildings_name'))
    )
    op.create_table('diaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_diaries_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diaries'))
    )
    op.create_table('user_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=30), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_activities_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_activities'))
    )
    op.create_table('memory_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('memory_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['memory_id'], ['campus_memories.id'], name=op.f('fk_memory_comments_memory_id_campus_memories')),
    sa.ForeignKeyConstraint(['parent_id'], ['memory_comments.id'], name=op.f('fk_memory_comments_parent_id_memory_comments')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memory_comments_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memory_comments'))
    )
    op.create_table('memory_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('memory_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['memory_id'], ['campus_memories.id'], name=op.f('fk_memory_likes_memory_id_campus_memories')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memory_likes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memory_likes')),
    sa.UniqueConstraint('memory_id', 'user_id', name='uq_memory_user_like')
    )
    op.create_table('comment_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['memory_comments.id'], name=op.f('fk_comment_likes_comment_id_memory_comments')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_comment_likes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comment_likes')),
    sa.UniqueConstraint('comment_id', 'user_id', name='uq_comment_user_like')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('memory_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['memory_comments.id'], name=op.f('fk_notifications_comment_id_memory_comments')),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], name=op.f('fk_notifications_from_user_id_users')),
    sa.ForeignKeyConstraint(['memory_id'], ['campus_memories.id'], name=op.f('fk_notifications_memory_id_campus_memories')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('campus_memories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('images', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('likes_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('comments_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campus_memories', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('comments_count')
        batch_op.drop_column('likes_count')
        batch_op.drop_column('images')

    op.drop_table('notifications')
    op.drop_table('comment_likes')
    op.drop_table('memory_likes')
    op.drop_table('memory_comments')
    op.drop_table('user_activities')
    op.drop_table('diaries')
    op.drop_table('buildings')
    # ### end Alembic commands ###
