"""empty message

Revision ID: b5ae00a23155
Revises: 
Create Date: 2026-01-30 22:50:17.302875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5ae00a23155'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campus_memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_campus_memories_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campus_memories'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campus_memories')
    # ### end Alembic commands ###
